# Generated by Django 3.1 on 2020-08-07 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0004_auto_20200807_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testcase.survey'),
            preserve_default=False,
        ),
    ]
