# Generated by Django 3.1 on 2020-08-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0006_surveysdone'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='relevant',
            field=models.BooleanField(default=False),
        ),
    ]
